### ISSUE TITLE
date columns are not included in interaction

### ISSUE THREAD

**Issue by javisantana** [CartoDB/Windshaft#103]
Create a layergroup including a date column in the interaction:

http://examples.cartodb.com/tiles/layergroup/39bd87a9c1a2ff02c52d192076ad3999:0/0/0/0/0.grid.json

```
 sql: 'select * from ne_10m_populated_p_2',
 cartocss: '#layer { marker-fill: black; line-color: #333; marker-width: 3 }',
 interactivity: 'cartodb_id, name, updated_at'

```

fetch a grid, update_at is not included

test with: 

```
curl 'http://examples.cartodb.com/tiles/layergroup?config=%7B%22version%22%3A%221.0.0%22%2C%22stat_tag%22%3A%22API%22%2C%22layers%22%3A%5B%7B%22type%22%3A%22cartodb%22%2C%22options%22%3A%7B%22sql%22%3A%22select%20*%20from%20ne_10m_populated_p_2%22%2C%22cartocss%22%3A%22%23layer%20%7B%20marker-fill%3A%20black%3B%20line-color%3A%20%23333%3B%20marker-width%3A%203%20%7D%22%2C%22cartocss_version%22%3A%222.1.0%22%2C%22interactivity%22%3A%5B%22cartodb_id%22%2C%22name%22%2C%22updated_at%22%5D%7D%7D%5D%7D&callback=jQuery17207429363711271435_1388760113074&_=1388760113193'
```

and fetching the tile:

```
curl "http://examples.cartodb.com/tiles/layergroup/39bd87a9c1a2ff02c52d192076ad3999:0/0/0/0/0.grid.json"
```

**Comment by inigomedina** [comment]
I'm closing this issue because it has been inactive for a long time. This probably means that it is not reproducible or it has been fixed in a newer version. If it's an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue.

Thank you!

**Comment by Algunenano** [comment]
For MVTs this is now handled by allowing dates to be requested as numbers. For other formats this has been stale for 4 years, so closing it.

**Comment by javisantana** [comment]
🥺

**Comment by Algunenano** [comment]
:bird:
