### ISSUE TITLE
Default to installed mapnik_version

### ISSUE THREAD

**Issue by gravitystorm** [CartoDB/Windshaft#117]
Grainstore accepts a mapnik version to default to for compiling styles, but this is left up to the end-user to provide in the options to the windshaft server.

It would be less surprising if Windshaft set it to the installed version of mapnik, by default. It's surprising to find Windshaft compiling the styles based on a version of mapnik that isn't going to be used by the server!

**Comment by Algunenano** [comment]
Stale
