### ISSUE TITLE
Give more details about mapnik rendering time

### ISSUE THREAD

**Issue by strk** [CartoDB/Windshaft#120]
Mapnik should have a way to report time spent in fetching data vs. time spent rendering. Not sure if this changed with recent introduction of "parallel fetching".

It may be useful to include detailed info about those steps in the X-Profile header.

JIRA REF: https://cartodb.atlassian.net/browse/CDB-1937

**Comment by Algunenano** [comment]
Introduced in 4.5.0 and, after some fixes, should be ready for production in 4.5.7.
