### ISSUE TITLE
Send stats about number of renderer caches invalidated by cache_buster

### ISSUE THREAD

**Issue by strk** [CartoDB/Windshaft#177]
It would be a useful information to know how many times a cached renderer gets invalidated by cache_buster.

\cc @zenitraM 

JIRA REF: https://cartodb.atlassian.net/browse/CDB-2750

**Comment by rochoa** [comment]
Stats is no longer a Windshaft responsibility, so this does not apply anymore.

BTW, number of renderers is actively reported by Windshaft-cartodb so this could be closed anyway.
