### ISSUE TITLE
Turn "req2param" profile into a block profile

### ISSUE THREAD

**Issue by strk** [CartoDB/Windshaft#183]
Right now we do not .start('req2param') and .end() when it's done.
As a result all profiling done under the "req2param" step do not appear as being _under_ the req2param step.

This makes graphite stats a bit confusing. We should switch to "block"-level profile.
I think this is the place:
https://github.com/CartoDB/Windshaft/blob/0.20.0/lib/windshaft/server.js#L478-L481

Rather than .done('req2param') it should .start('req2param') and .end() where it calls .done() now. The interface kind of sucks because doing the switch would remove the "req2param" label from the X-Tiler-Profiler header, but that's probably never shown much more than the time between the last inner step and the return...

@rochoa note that this change would require a new Windshaft release _or_ Windshaft-CartoDB requiring a specific commit in Windshaft repo...

**Comment by rochoa** [comment]
I see no need to to this.
