### ISSUE TITLE
Limit number of tables and layers in layergroups

### ISSUE THREAD

**Issue by rochoa** [CartoDB/Windshaft#223]
Maximum number of tables in a visualisation will be limited to 10.
Maximum number of layers in a visualisation will be limited to 10.

For the initial release we will increment in graphite a counter when any of the limits is reached.

As the initial release is kind of risky it will be possible to override the numbers in a per user basis.

**Comment by xavijam** [comment]
:dancer:

**Comment by iriberri** [comment]
Oh, my nice 15 layers map will die :(

**Comment by Algunenano** [comment]
Stale
