### ISSUE TITLE
Retina support

### ISSUE THREAD

**Issue by rochoa** [CartoDB/Windshaft#243]
Add retina support for tiles
- [x] Mapnik: use `@2x` notation.
- [ ] HTTP.
  - [ ] support for different tiles sizes so:
  - [ ] a translation from non-retina to retina-url / support in mapconfig can be applied.
- [ ] Torque: png renderer.
- [ ] Plain renderer.
  - [ ] Image background scaled.
-  [ ] Provide correct image size via options.
- [ ] Blend support.
  - [ ] Accept tile size via options.

**Comment by rochoa** [comment]
Support for mapnik layers was added in https://github.com/CartoDB/Windshaft/pull/247

**Comment by Algunenano** [comment]
Stale
