### ISSUE TITLE
when creating raster layergroup interactivity is allowed but it fails

### ISSUE THREAD

**Issue by javisantana** [CartoDB/Windshaft#244]
if you create a map with 
```
{
    "layers": [
        {
            "options": {
                "cartocss": "#pop { raster-opacity: 0.2; }",
                "cartocss_version": "2.3.0",
                "geom_column": "the_raster_webmercator",
                "geom_type": "raster",
                "interactivity": [
                    "cartodb_id"
                ],
                "sql": "select * from pop"
            },
            "type": "cartodb"
        }
    ],
    "stat_tag": "API",
    "version": "1.0.0"
}
```

it works but if you requests grid.json tiles they raise an error:

```
error: "Postgis Plugin: ERROR: column "cartodb_id" does not exist LINE 1: ...ECT ST_AsBinary("the_raster_webmercator") AS geom,"cartodb_i... ^ in executeQuery Full sql was: 'SELECT ST_AsBinary("the_raster_webmercator") AS geom,"cartodb_id" FROM (select * from o_4_pop) as cdbq WHERE "the_raster_webmercator" && ST_SetSRID('BOX3D(-20037508.3 -1252344.271424327,1252344.271424327 20037508.3)'::box3d, 3857) LIMIT 1165535' "
```

I guess is because cartodb_id is not selected.

The question here is. Shouldn't that anonymous map fail in the creation? does make sense to have interactivity for raster ?

**Comment by rochoa** [comment]
This happens because cartodb_id is not created in the overviews but as you are pointing it does not make sense to have interactivity in raster layers so I propose to throw an error if `geom_type` is raster and the layer is defined with interactivity.

What do you think?

**Comment by javisantana** [comment]
ok for that, I'd say the same for torque

**Comment by rochoa** [comment]
In the case of torque layers: do we want to throw an error or we just ignore if an interactivity option is given?

It could be as easy as:

```patch
diff --git a/lib/windshaft/renderers/torque/factory.js b/lib/windshaft/renderers/torque/factory.js
index 48d0432..ac91fec 100644
--- a/lib/windshaft/renderers/torque/factory.js
+++ b/lib/windshaft/renderers/torque/factory.js
@@ -83,6 +83,11 @@ TorqueFactory.prototype = {
             callback(new Error("layer " + layer + " is not a torque layer"));
             return;
         }
+
+        if ( layerObj.options.interactivity ) {
+            throw new Error("Torque layers do not support interactivity");
+        }
+
         var pgSQL = sql(dbParams, this.sqlClass);
         fetchMapConfigAttributes(pgSQL, mapConfig, dbParams, layer, function(err, params){
             if (err) {
```

In the mapnik I see useful to throw an error because interactivity is an optional property and doesn't make sense always. However in torque it does not even apply, so... wouldn't it be better to just remove from the torque layer options documentation: https://github.com/CartoDB/Windshaft/blob/master/doc/MapConfig-1.3.0.md#22-torque-layers-options?

**Comment by javisantana** [comment]
for me in an error, torque interaction should be client side
