### ISSUE TITLE
Mapnik logs should get into application logs instead of stdout

### ISSUE THREAD

**Issue by rochoa** [CartoDB/Windshaft#245]
Example of log that goes to stdout https://github.com/mapnik/mapnik/blob/2.3.x/src/marker_cache.cpp#L222-L225

**Comment by rochoa** [comment]
cc/ @lbosque

**Comment by Algunenano** [comment]
I think this is now handled automagically by `systemd` (logs to journalctl) so it shouldn't be an issue
