### ISSUE TITLE
Blank

### ISSUE THREAD

**Issue by zenitraM** [CartoDB/Windshaft#251]
Wrong repo

**Comment by zenitraM** [comment]
I found a PPA with p551:
https://launchpad.net/~brightbox/+archive/ubuntu/ruby-ng-experimental

and also found this funny thing:
https://www.ruby-lang.org/en/news/2014/11/13/ruby-1-9-3-p551-is-released/

"Ruby 1.9.3 is now in the security maintenance phase. This means that we never fix bugs except for security issues. And, at this time, the end of the maintenance of 1.9.3 has been scheduled for February next year. We recommend that users of Ruby 1.9.3 should migrate to a newer version as soon as possible."

**Comment by rafatower** [comment]
The problem is more serious than I thought. We are using files from 1.9.1 rather than 1.9.3 in some cases:
https://github.com/CartoDB/cartodb/issues/1857
