### ISSUE TITLE
NODATA (0) renders black when pulling rasters from PostGIS

### ISSUE THREAD

**Issue by averas** [CartoDB/Windshaft#252]
I have generated some DEM and hillshade (GeoTIFF) rasters that I try to render via Windshaft (pulled out of PostGIS), however NODATA pixels always render as black. If I take the same rasters (although files read via GDAL) they render fine (i.e. NODATA rendered as transparent) in both tilemill and node-mapnik. Could this be caused by the rasters coming out of PostGIS, or is Windshaft doing something wrong here?

Another thing I've noticed is that if I use a 16BUI (grayscale) data type for my rasters they again yield an odd result via Windshaft, while they render fine via tilemill and node-mapnik. If I translate the rasters to 8BUI (Byte) they render fine (aside from the black NODATA) in Windshaft as well as in tilemill and node-mapnik..

Any clues as to what's going on here?

**Comment by Algunenano** [comment]
Stale
