### ISSUE TITLE
plain layers with pattern does not render properly

### ISSUE THREAD

**Issue by javisantana** [CartoDB/Windshaft#269]
"plain" layers allows to set an "image" as background pattern, when you use one of them for render a static map you get an error like "wrong background color".

Check this viz.json for an example
https://osm2.cartodb.com/api/v2/viz/feeaae54-9e89-11e4-ba3a-0e853d047bba/viz.json

**Comment by rochoa** [comment]
What is the expected behaviour in terms of image positioning?

I mean, do we have to fill/stretch/fit/center the image?

**Comment by rochoa** [comment]
I guess the behaviour has to be the same as the one in CSS' image-background default behaviour, right?

The issue I see here is that the background is fixed and the tiles keeps moving/panning on top of if.

![background](https://cloud.githubusercontent.com/assets/45346/6287573/d9b203be-b912-11e4-9b49-fa6303518f65.gif)

**Comment by javisantana** [comment]
yes, pattern. I wouldn't worry about the position of the pattern

**Comment by rochoa** [comment]
OK :+1:
