### ISSUE TITLE
How to style without long URLs?

### ISSUE THREAD

**Issue by christianbundy** [CartoDB/Windshaft#285]
I'm working on an application that's styling tiles on the fly, but our URLs are getting unreasonable. Currently we have urls with 25,000+ characters defining custom styles. What's the recommended way to define complex custom styles without having *huge* URL strings? Thanks!

**Comment by rochoa** [comment]
Have a look at the [Multilayer API](https://github.com/CartoDB/Windshaft/blob/master/doc/Multilayer-API.md) documentation and also to the [MapConfig specification](https://github.com/CartoDB/Windshaft/blob/master/doc/MapConfig-specification.md).

Basically allows you to create different tiles with different layers and different options for each of them.

If your problem involves modifying some values like filters in the SQL query or properties in the CartoCSS I recommend you to check [Windshaft-cartodb's named maps](https://github.com/CartoDB/Windshaft-cartodb/blob/master/docs/Map-API.md#named-maps-1) as it has support for templates and aims to solve those scenarios.

hope that helps

**Comment by christianbundy** [comment]
Thanks @rochoa, that helps a lot!

**Comment by rochoa** [comment]
No problem! :wink:
