### ISSUE TITLE
Points in torque tile boundaries

### ISSUE THREAD

**Issue by rochoa** [CartoDB/Windshaft#308]
What tiles should get a point that is just in the apex of two tile boundaries?

In particular: having a `(0,0)` point in tiles `TL`, `TR`, `BL`, `BR`, which tile should get the point?

```
     ---------
    | TL | TR |
    |--(0,0)--|
    | BL | BR |
     ---------
```

**Comment by rochoa** [comment]
I just added a test so we can track the behaviour if we plan to change it: https://github.com/CartoDB/Windshaft/commit/1d04fac5a7157039bc623c4f94b88833ec09717f

**Comment by rochoa** [comment]
To remove the point from the `BL` tile we can do something like:

```patch
diff --git a/lib/windshaft/renderers/torque/renderer.js b/lib/windshaft/renderers/torque/renderer.js
index d4e0643..bace06e 100644
--- a/lib/windshaft/renderers/torque/renderer.js
+++ b/lib/windshaft/renderers/torque/renderer.js
@@ -92,7 +92,7 @@ Renderer.prototype = {
                 ymax: ymax,
                 b_xmin: xmin - (pixres * buffer),
                 b_ymin: ymin + (pixres * buffer),
-                b_xmax: xmax + (pixres * buffer),
+                b_xmax: xmax + (pixres * buffer) - pixres,
                 b_ymax: ymax - (pixres * buffer),
                 b_size: buffer / attrs.resolution
             };
```

We will have some regressions in torque_boundaries suite.

**Comment by rochoa** [comment]
cc @javisantana @andrewxhill @fdansv as you were part of the original discussion/issue.

**Comment by rochoa** [comment]
Probably we should define this kind of things in https://github.com/andrewxhill/tilecubes/blob/master/2.0/spec.md

**Comment by ohasselblad** [comment]
`What tiles should get a point that is just in the apex of two tile boundaries?` 

TR should get it!

**Comment by Algunenano** [comment]
Stale
