### ISSUE TITLE
Grid.json returning different values at random

### ISSUE THREAD

**Issue by zenitraM** [CartoDB/Windshaft#310]
From SB #4901269:

This tile grid.json:

https://cartocdn-ashbu.global.ssl.fastly.net/tnris/api/v1/map/929b0b00a3470c896e8290b3c62351ca:1424894996987.25/0/12/916/1657.grid.json?callback=grid

returns either "Cedar bend" or "Baird" or sometimes "Adell" as quadname, at random. (change the callback value to skip the cache).

Could be related with metatiling

**Comment by zenitraM** [comment]
cc @iriberri

**Comment by iriberri** [comment]
Subscribing.

**Comment by zenitraM** [comment]
Bump - this is happening now with this grid.json:

https://cartocdn-ashbu.global.ssl.fastly.net/tnris/api/v1/map/c98d78e12e8d09a0cdc0ebea1935aa7d:1433366258063.22/0/12/892/1657.grid.json

It returns "Lorraine" or "Knott NE", at random (try different cache-busters).
See ticket for URL to reproduce this

**Comment by javisantana** [comment]
what is the map? it would be nice to have it to reproduce the problem

**Comment by rochoa** [comment]
I'm unable to get the different response:
```
$ for i in {1..25}; do curl -s "https://cartocdn-ashbu.global.ssl.fastly.net/tnris/api/v1/map/c98d78e12e8d09a0cdc0ebea1935aa7d:1433366258063.22/0/12/892/1657.grid.json?buster=$i" | openssl sha1 ; done
2675746f7979ac877826033ef6d458de4cebb07f
2675746f7979ac877826033ef6d458de4cebb07f
2675746f7979ac877826033ef6d458de4cebb07f
2675746f7979ac877826033ef6d458de4cebb07f
2675746f7979ac877826033ef6d458de4cebb07f
2675746f7979ac877826033ef6d458de4cebb07f
2675746f7979ac877826033ef6d458de4cebb07f
2675746f7979ac877826033ef6d458de4cebb07f
2675746f7979ac877826033ef6d458de4cebb07f
2675746f7979ac877826033ef6d458de4cebb07f
2675746f7979ac877826033ef6d458de4cebb07f
2675746f7979ac877826033ef6d458de4cebb07f
2675746f7979ac877826033ef6d458de4cebb07f
2675746f7979ac877826033ef6d458de4cebb07f
2675746f7979ac877826033ef6d458de4cebb07f
2675746f7979ac877826033ef6d458de4cebb07f
2675746f7979ac877826033ef6d458de4cebb07f
2675746f7979ac877826033ef6d458de4cebb07f
2675746f7979ac877826033ef6d458de4cebb07f
2675746f7979ac877826033ef6d458de4cebb07f
2675746f7979ac877826033ef6d458de4cebb07f
2675746f7979ac877826033ef6d458de4cebb07f
2675746f7979ac877826033ef6d458de4cebb07f
2675746f7979ac877826033ef6d458de4cebb07f
2675746f7979ac877826033ef6d458de4cebb07f
```

**Comment by rochoa** [comment]
This is the layer config:
```
"options": {
  "cartocss": "@fill: #0237c9;\n//@halo: #bcd1f2;\n@halo: lighten(desaturate(@fill, 50%), 50%);\n\n#usgs_doq_names_wgs84[zoom>=8]{\n  polygon-opacity: 0;\n  line-comp-op: overlay;\n  ::outline {\n    line-color: @halo;\n    line-opacity: 1;    \n    [zoom >= 8] {\n      line-width: 2;\n      line-opacity: 1;\n    }\n    [zoom >= 9] {\n      line-width: 2.5;\n    }\n    [zoom >= 10] {\n      line-width: 3.4;\n    }\n    [zoom >= 11] {\n      line-width: 4;\n    }\n    [zoom>=12] {\n      line-width: 5;\n    }\n  }\n  ::inline {\n    line-color: @fill;\n    line-opacity: 1;\n    [zoom >= 8] {\n      line-width: .7;\n    }\n    [zoom >= 9] {\n      line-width: 1.2;\n    }\n    [zoom >= 10] {\n      line-width: 1.4;   \n    }\n    [zoom >= 11] {\n      line-width: 1.6;\n    }\n    [zoom>=12] {\n      line-width: 1.8;\n    }\n  }\n\n}",
  "cartocss_version": "2.1.1",
  "interactivity": "cartodb_id,c_lat,c_lon,closest_county_name,quadnum,quadname",
                "sql": "select * from usgs_doq_names_wgs84"
},
```

**Comment by rochoa** [comment]
https://cartocdn-ashbu.global.ssl.fastly.net/tnris/api/v1/map/c98d78e12e8d09a0cdc0ebea1935aa7d:1433366258063.22/0/12/902/1657.png
vs
https://cartocdn-ashbu.global.ssl.fastly.net/tnris/api/v1/map/c98d78e12e8d09a0cdc0ebea1935aa7d:1433366258063.22/0/12/902/1657.grid.json

OR 

Loraine vs Howard

**Comment by rochoa** [comment]
http://tnris.cartodb.com/api/v1/sql?q=select%20cartodb_id,c_lat,c_lon,closest_county_name,quadnum,quadname%20from%20usgs_doq_names_wgs84%20where%20the_geom_webmercator%20%26%26%20CDB_XYZ_Extent(902,1657,12)

https://cartocdn-ashbu.global.ssl.fastly.net/tnris/api/v1/map/c98d78e12e8d09a0cdc0ebea1935aa7d:1433366258063.22/0/12/902/1657.grid.json?buster

The correct one seems to be Loraine.

**Comment by rochoa** [comment]
Well... this seems totally related to how metatile cache is organized.

See:
 - https://github.com/CartoDB/tilelive-mapnik/blob/cdb/lib/render.js#L103
 - https://github.com/CartoDB/tilelive-mapnik/blob/cdb/lib/render.js#L118
 - https://github.com/CartoDB/tilelive-mapnik/blob/cdb/lib/render.js#L132

So when several tiles are queued to the server their callback consume the same grid.json as their pixel representation is the same because all the grids are empty in that layer.

This is not an easy thing to fix so as an alternative in this map would be to merge layers 0 (grid) and 2 (labels) so they have different keys in the grid.

Thanks @zenitraM for your help!

**Comment by rochoa** [comment]
Confirming this, pixel key is the same:

```
[2015-06-24 15:00:44.237] [INFO] console - pixel_key 3
[2015-06-24 15:00:44.238] [INFO] [default] - undefined GET development.localhost.lan:8181/api/v1/map/d1f438544c2af1f25995423750a7c7db:1435148707900.95/0/12/902/1657.grid.json 200 7 ms ({"req2params":2,"render-grid-json":5,"encode":1,"render":1,"total":7}) -> application/json; charset=utf-8
[2015-06-24 15:00:46.713] [INFO] console - pixel_key 3
[2015-06-24 15:00:46.714] [INFO] [default] - undefined GET development.localhost.lan:8181/api/v1/map/d1f438544c2af1f25995423750a7c7db:1435148707900.95/0/12/892/1657.grid.json 200 6 ms ({"req2params.setup":1,"render-grid-json":5,"encode":0,"render":1,"total":6}) -> application/json; charset=utf-8
```

So two requests *happening at the same time* will get the same cached tile, which is incorrect.

**Comment by iriberri** [comment]
Writing here. @rochoa decided to disable the grid optimization.
