### ISSUE TITLE
when you don't set subdomains using http layers tiles fail

### ISSUE THREAD

**Issue by javisantana** [CartoDB/Windshaft#321]
If you have a layergroup with a layer like this:

```
 {
                type: "http",
                urlTemplate: "http://{s}.basemaps.cartocdn.com/light_nolabels/{z}/{x}/{y}.png"
              
 }
```

the instanciation works (http://examples.cartodb.com/api/v1/map?stat_tag=API&config=%7B%22version%22%3A%221.0.0%22%2C%22stat_tag%22%3A%22API%22%2C%22layers%22%3A%5B%7B%22type%22%3A%22http%22%2C%22options%22%3A%7B%22urlTemplate%22%3A%22http%3A%2F%2F%7Bs%7D.basemaps.cartocdn.com%2Flight_nolabels%2F%7Bz%7D%2F%7Bx%7D%2F%7By%7D.png%22%7D%7D%2C%7B%22type%22%3A%22cartodb%22%2C%22options%22%3A%7B%22sql%22%3A%22select%20*%20from%20country_boundaries%22%2C%22cartocss%22%3A%22%23layer%20%7B%20polygon-fill%3A%20%23F00%3B%20polygon-opacity%3A%200.3%3B%20line-color%3A%20%23F00%3B%20%7D%22%2C%22cartocss_version%22%3A%222.1.0%22%7D%7D%2C%7B%22type%22%3A%22http%22%2C%22options%22%3A%7B%22urlTemplate%22%3A%22http%3A%2F%2F%7Bs%7D.tile.stamen.com%2Ftoner-labels%2F%7Bz%7D%2F%7Bx%7D%2F%7By%7D.png%22%2C%22subdomains%22%3A%5B%22a%22%2C%22b%22%2C%22c%22%5D%7D%7D%5D%7D&callback=_cdbc_2956533816_1)

but when you fetch a tile it fails with a json error:

```
{
error: "Cannot read property 'length' of undefined"
}
```

We have two options here:

1- use a default subdomains
2- raise an error is {s} is set in the template and no subdomains are set

I'd go with the most explicit version (2) but I don't know the internals

**Comment by rochoa** [comment]
My fault, I didn't implement it correctly: https://github.com/CartoDB/Windshaft/blob/master/doc/MapConfig-1.3.0.md

It should:
```
Defaults to ['a', 'b', 'c'] when {s} is present in `urlTemplate`, [] otherwise.
```
