### ISSUE TITLE
Not throwing errors on incorrect database credentials

### ISSUE THREAD

**Issue by christianbundy** [CartoDB/Windshaft#322]
I've been pulling my hair out for the past few days trying to get Windshaft to connect to a remote PostgreSQL database, but after trying to use completely false information (user: "alsjkdfaklsd", password: "lakjlaskdjf", host: "lawjaldsfkj", database: "asldkjfaslkdfja", etc.), I've realized that Windshaft doesn't throw any errors when you use the wrong database credentials, so there doesn't seem to be any way to debug a faulty DB connection.

I can't find a way to see whether or not I'm even connected to a database. Every URL I try just gives me "Cannot GET /some/url/that/doesnt/matter/", except for `/` which welcomes me to Windshaft.

How can I troubleshoot my PostgreSQL connection? Also, where should I be putting my database credentials? I'm not sure if they should be in `config/environments/development.js`, my `server_options.js` file, or somewhere else.

Thanks!

**Comment by rochoa** [comment]
Hi @christianbundy,

Database connection params can be provided in server_options, in windshaft-cartodb we do it in `req2params` method, have a look here: https://github.com/CartoDB/Windshaft-cartodb/blob/master/lib/cartodb/server_options.js#L609-L614

When implementing your `req2params` function in server options you can pull the credentials from the configuration environment file.

Hope that helps.

**Comment by christianbundy** [comment]
Thanks @rochoa. I had it set in `server_options.js`, but I've also set it in `req2params.js` (and can verify that it's set with `console.log`).

``` javascript
req2params: function(req, callback){

  // returns "db postgres password 5432"
  console.log(dbhost, dbuser, dbpassword, dbport);  

  // this is in case you want to test sql parameters eg ...png?sql=select * from my_table limit 10
  req.params =  _.extend({}, req.params);
  _.extend(req.params, req.query);

  // increment number of calls counter
  // NOTE: "this" would likely point to the server instance
  this.req2params_calls = this.req2params_calls ? this.req2params_calls + 1 : 1;

  callback(null,req);
}
```

I've set `db` in `/etc/hosts`, but changing the host to `127.0.0.1`, `localhost`, or `google.com` yields the exact same result: no errors, and no connectivity. I've tried injecting `console.log` statements in [the `ctor` function](https://github.com/CartoDB/Windshaft/blob/2c1def1957acc4454892b666413961a005c18d94/lib/windshaft/renderers/torque/psql_adaptor.js#L2-L4), and it looks like they never even get called either. Where should I be looking for errors, and what should they look like?

I understand that we're using [node-cartodb-psql](https://github.com/CartoDB/node-cartodb-psql), but injecting a `console.log` statement at the top of [the `PSQL` function](https://github.com/CartoDB/node-cartodb-psql/blob/0.4.0/lib/psql.js#L82-L305) shows that it's not being called either.

I'm sure that *something* is misconfigured, but I'm not sure how to troubleshoot my issue.

**Comment by christianbundy** [comment]
I've open-sourced my code on the off chance that I'm doing something especially obvious: https://github.com/TerraSeer/windshaft-terraseer

**Comment by christianbundy** [comment]
I didn't realize that the API consumption had completely changed since the last time I've used this – I was trying to consume `/database/:database/table/:table/:x/:y/:z.*`, whereas it looks like you've migrated to something like `/database/:database/layergroup/:token/:x/:y/:z.*` after an API call to request a token. I'll close this issue.

**Comment by rochoa** [comment]
Sorry, my fault for not considering you were in that scenario.

If you want to keep using the old approach you can stick to version 0.40.0, see 0.41.0 release notes: https://github.com/CartoDB/Windshaft/blob/master/NEWS.md#version-0410

We are not yet there but we will release a 1.0.0 version at some point so this breaking changes are handled with major versions releases only. Sorry about it.
