### ISSUE TITLE
'postgres' is undefined

### ISSUE THREAD

**Issue by lliss** [CartoDB/Windshaft#328]
```
var COLUMN_NAME_DEFAULT = global.environment.postgres.geometry_field || 
TypeError: Cannot read property 'postgres' of undefined
```
I found this issue but it doesn't seem to actually address the problem.
https://github.com/CartoDB/Windshaft/issues/288

I'm using a setup similar to the one documented in 
https://github.com/CartoDB/Windshaft/blob/master/README.md

What is the proper configuration format to pass the column name?

**Comment by yanc0** [comment]
I get rid of this problem by setting global var at the very top of app.js
```
global.environment  = require('./config/environments/devel.js');
```

**Comment by rochoa** [comment]
This should no longer be a problem as mapnik/factory.js does not rely anymore in those globals: https://github.com/CartoDB/Windshaft/blob/34267dd04395431e13cd9f6b4c1e7ea0b382e122/lib/windshaft/renderers/mapnik/factory.js
