### ISSUE TITLE
Add more datasources

### ISSUE THREAD

**Issue by BHare1985** [CartoDB/Windshaft#334]
Since the underlying map image rendering is Mapnik, would it be possible to utilize mapnik's OGR support to allow non postgres databases? I feel this would really add to the value of Windshaft.
 
I would love MSSQL support.

**Comment by rochoa** [comment]
Although Windshaft's motto has been "A Node.js map tile server for **PostGIS** with CartoCSS styling." for a while it's true that recently we've started to implement other datasources. For example the HTTP, plain renderers.

So it should be possible to implement a mapnik's OGR with other datasource/database as backend as far as it follows the following spec: https://github.com/CartoDB/Windshaft/blob/master/lib/windshaft/renderers/README.md

You can check how the HTTP renderer is built following those interfaces: https://github.com/CartoDB/Windshaft/tree/master/lib/windshaft/renderers/http

It would be wonderful if you can prototype something with OGR, I would be more than happy to help :open_hands:

**Comment by rochoa** [comment]
Hey Brian,

Did you have the time to prototype something? :ear: 

raul

**Comment by BHare1985** [comment]
Actually, I forked from an older but more manageable version of Windshaft and got that to work using the newest mapnik which allows me complete flexibility. Just had to get grainstore and all its depencies to be windows friendly.

https://github.com/BHare1985/Windshaft 

 I'd love to spend some time on getting the latest Windshaft with mapnik 2.x to accept non-postgis, but don't have the time right now. This can be closed (if you want) because my needs have been met.

**Comment by rochoa** [comment]
Cool! Thanks for letting me know.

Just to understand better why you had to fork: what problems did you find with the current approach? I'm thinking in making some changes and would like to hear from other users.

**Comment by BHare1985** [comment]
Well it was mostly a time constraint. Latest windshaft is a beast (hard to manage but good efficiency), and I just needed a relatively simple and semi-efficient method for doing dynamic map generation that works with Windows. Everything in Windshaft is geared at linux installation and use, figured this was the easier route.

I am still having issues with millstone and windows  ( https://github.com/mapbox/millstone/issues/122 ) and I had to submit a few issue requests to mapbox team for their zip library (they are great).

Instead of relying on hiredis for redis-mpool, I just opted for the native javascript method, which was only a performance decrease of like 10-20% but it was like instead of doing 300,000 read/write a second you can only do 270,000 a second, which I figured wouldn't hurt my bottom line for the specific use-case of redis

**Comment by rochoa** [comment]
Nice to hear from you. Your choices totally make sense based on your comments! :+1: And yes, it's not a problem to use redis js impl.

Again, thanks for sharing your insights. At some point Windshaft should be more like a library than a library+service, so it could be easier to integrate and reuse in other projects.
