### ISSUE TITLE
Renderer selection should be based on layer and not in format

### ISSUE THREAD

**Issue by rochoa** [CartoDB/Windshaft#336]
Right now the renderer selection happens based on the `format` requested for `{layergroupid}/{layerid}/{z}/{x}/{y}.{format}` URLs, that has some limitations and in general is not clear.
See https://github.com/CartoDB/Windshaft/blob/master/lib/windshaft/renderers/renderer_factory.js#L39-L43

So for instance if you want to retrieve an `http` layer in `png` format, let's say layer 0, you have to `GET /:layergroupid/0/0/0/0.http.png` because `GET /:layergroupid/0/0/0/0.png` will get you the all the mapnik layers because the `png` format is attached to that format.

It would be much nicer that the requested layer will render base on the format if it has a renderer for that format and throw an error if it doesn't.

With layers:
```
0 = http
1 = mapnik
2 = mapnik
3 = torque
```

I would expect the following requests to behave like:
```
GET /:layergroupid/0/0/0.png           => no layer selection, all mapnik layers to be backwards compatible
GET /:layergroupid/0/0/0/0.png         => http layer as png image 
GET /:layergroupid/0/0/0/0.json        => 400 as http layers don't have a json renderer
GET /:layergroupid/1/0/0/0.png         => render mapnik layer 1 (alone) as png, this a backwards incompatible change but I guess no one was using these urls to request all mapnik layers as png.
GET /:layergroupid/1/0/0/0.grid.json   => mapnik grid, as it is now. it make sense to keep the *grid* notation as it is not only json but with a grid format.
GET /:layergroupid/3/0/0/0.png         => it will render the torque layer as a png layer as torque has a png renderer
GET /:layergroupid/3/0/0/0.torque.json => torque json format, as it is now. same as in grid.json

**Comment by rochoa** [comment]
^^ @javisantana @alonsogarciapablo

**Comment by javisantana** [comment]
the * are because of formatting or part of the actual url?

**Comment by rochoa** [comment]
Just to highlighting them, probably better to remove them. Sorry.
