### ISSUE TITLE
Extend multilayer layer selection

### ISSUE THREAD

**Issue by rochoa** [CartoDB/Windshaft#337]
Right now with a layergroupid it's possible to request a layer or `all` layers with requests like `GET {layergroupid}/0/{z}/{x}/{y}.{format}` or `GET {layergroupid}/all/{z}/{x}/{y}.{format}`.

This proposes to extend the behaviour of the `{layerid}` *param* to accept a multiple selection, so it would be possible to request something like: `GET {layergroupid}/0,2,4/{z}/{x}/{y}.{format}`.

Imagine layers:
```
0 = http
1 = mapnik
2 = mapnik
3 = mapnik
4 = torque
5 = torque
```

Some issues/problems I can advance:

#### Ordering

With the current approach when you request `GET {layergroupid}/{z}/{x}/{y}.{format}` or `GET {layergroupid}/all/{z}/{x}/{y}.{format}` all the mapnik layers are rendered with a unique mapnik renderer.

Now we could request `GET {layergroupid}/2,1/{z}/{x}/{y}.{format}` which will imply creating a new mapnik renderer.

#### Grouping/blending

Now it would be possible to modify the order and group different layers in different order (it's kind of the same problem as in *Ordering*).

A `GET {layergroupid}/0,1,2,4,3/{z}/{x}/{y}.{format}` request means we need to create two new mapnik renderers one for `1,2` and another for `3`.

If we do this the behaviour of `all` should match and layer definition ordering should be always considered because right now when you request "all" layers the mapnik layers are blended all together in the position the first mapnik layer is found.

#### Format unification
This is more like a question: should we support for instance something like `GET {layergroupid}/2,1/{z}/{x}/{y}.grid.json` so it's possible to request multiple grids in the same request, returning an array of grid.jsons. Or ... `GET {layergroupid}/5,4/{z}/{x}/{y}.torque.json` more or less the same for torque layers.

In this scenario if requested format is not present in all layers it will result in a 400 error, for instance ``GET {layergroupid}/2,5/{z}/{x}/{y}.grid.json` will throw 400 as layer `5` does not support grid.json format.

**Comment by rochoa** [comment]
^^ @javisantana @alonsogarciapablo

**Comment by alonsogarciapablo** [comment]
Another solution that @javisantana and I discussed the other the day was to add the following endpoint:

`GET {layergroupid}/raster/{z}/{x}/{y}.{format}`

This would render all layers of type raster (all layers except the torque ones). This way we (cartodb.js) wouldn't need to know the layers and types of layers of a map (we currently don't have this information in the client for named maps).

What do you think @rochoa?

**Comment by rochoa** [comment]
I'm OK with that :+1:

But ... for doing that we still need to solve some of the problems. Asking for `raster` is no more than an alias, like the one we have right now for `all`.

**Comment by alonsogarciapablo** [comment]
@rochoa, good work! Are we planning to add the `raster` alias this milestone? Thanks!

**Comment by rochoa** [comment]
That's a good question :-). And I got another: what kind of layers do we consider as `raster`?

cc @javisantana

**Comment by javisantana** [comment]
for me: http, mapnik and plain ones.

What do you think?

**Comment by rochoa** [comment]
I was guessing that was about to be your answer :smiley:. However I don't like the alias `raster` because torque is kind of `raster`ish, isn't it? :trollface:

**Comment by alonsogarciapablo** [comment]
http, mapnik, and plain layers -> `static`
torque layers -> `dynamic`

What about the following?
```
GET {layergroupid}/static/{z}/{x}/{y}.{format}
```

**Comment by rochoa** [comment]
I don't want to look like a troll but `mapnik` is also `dynamic` :-(

**Comment by rochoa** [comment]
OK, as we don't see what is better here we won't implement any alias for now. The client will be responsible to select the layers, which can be based on the metadata, see https://github.com/CartoDB/Windshaft/pull/341
