### ISSUE TITLE
Allow client to request specific png format

### ISSUE THREAD

**Issue by d4weed** [CartoDB/Windshaft#344]
In certain scenarios it would be very useful being able to get the tiles in PNG32 (or 24) instead of PNG8.

The reason is that at times you need to be absolutely certain that the colors generated in cartoCSS are persistent, for example, when you do canvas processing of the tiles and need to encode values in the color palette. Currently the colors vary slightly from tile to tile

**Comment by dgaubert** [comment]
Taking this one!

**Comment by d4weed** [comment]
Oh yeah!

http://i.imgur.com/gsFyUXe.gifv

**Comment by rochoa** [comment]
This was implemented in [1.2.0](https://github.com/CartoDB/Windshaft/releases/tag/1.2.0) release.

**Comment by rochoa** [comment]
Big kudos to @dgaubert !!! :ship: ing :it:
