### ISSUE TITLE
Overlays support

### ISSUE THREAD

**Issue by rochoa** [CartoDB/Windshaft#355]
A new layer type should be supported to allow adding overlays similar to the ones you can do with the CartoDB editor but rendered server side.
- [ ] Decide supported overlays
- [ ] Look for alternatives to render them server side: https://github.com/CartoDB/Windshaft/wiki/Overlays-support
- [ ] Have a prototype for at least one supported overlay

**Comment by rochoa** [comment]
I'm removing this issue from "Los Navalmorales" milestone as we are working on a html2canvas client side solution.

See https://github.com/CartoDB/cartodb/issues/4014

**Comment by dprophet** [comment]
Whats the status of this item?

**Comment by Algunenano** [comment]
Stale
