### ISSUE TITLE
Add support for background image layer at named maps

### ISSUE THREAD

**Issue by Kartones** [CartoDB/Windshaft#362]
A definition for `background` layers with an image (`options` -> `image` is not empty at layer opts) is missing to be able to support them.

Up to you the format, if a new type, having a specific property instead of color, or any alternative you see best.

Relates to https://github.com/CartoDB/cartodb/issues/4130

**Comment by rochoa** [comment]
Related to https://github.com/CartoDB/Windshaft/issues/269
