### ISSUE TITLE
Pre-render cartocss-styled tiles / images on the server?

### ISSUE THREAD

**Issue by fullofcaffeine** [CartoDB/Windshaft#370]
Is it possible to create a heatmap like this one: 

![heatmap_urban_us_east](https://cloud.githubusercontent.com/assets/81248/8841101/5c50d2c8-30af-11e5-9b3e-a8a07bff9b95.png)

Using Mapnik/Widshaft and CartoCSS but pre-render it on the server, and serve it tiled? Is it something `cartocss` and `windshaft` could do?

**Comment by javisantana** [comment]
creating a heatmap is possible with cartocss (you can generate a heatmap in cartodb and see the css) but prerender is not possible.

For these kind of questions is better to go to stackoverflow and tag the question as cartodb

**Comment by fullofcaffeine** [comment]
@javisantana Cool, I'll use stackoverflow next time. Thanks!
