### ISSUE TITLE
Issuing my query not in a subquery.

### ISSUE THREAD

**Issue by lghamie** [CartoDB/Windshaft#372]
When the full query gets arranged by Windshaft, having my query in the subquery named  'cdbq' prevents it from using the correct index. 

If I try (via psql) my query, adding the conditions that Windshaft adds, eg. 'AND "location" && ST_MakeEnvelope(....)'  as part of my WHERE clause, it uses the desired index.

Is there any way to do this? Is there any part of the code I could override to do this? I tried grepping through it but couldn't find what I was looking for.

Thanks for this great software!

**Comment by javisantana** [comment]
how do you know it's not using the index? postgres should guess even in a subquery

**Comment by lghamie** [comment]
Hi Javi, I'm using EXPLAIN on pgAdmin, and it shows a seq scan on the one with a subquery, while it shows a Index Scan in the plain-query one. 

My sub-query uses a group by on the 'geom' field, that's probably  the cause.

**Comment by javisantana** [comment]
could you post your query?

**Comment by javisantana** [comment]
I think you could avoid the seq scan filtering before using !bbox! special token

**Comment by lghamie** [comment]
Great. Using !bbox! solved it.

Thanks!

**Comment by javisantana** [comment]
Could you share a little bit more about your query?

**Comment by lghamie** [comment]
Yeah, absolutely
```sql
SELECT AVG(value) as avgValue,
   ST_MakeEnvelope(
       TRUNC(cast(ST_X(location) as numeric), 3), 
       TRUNC(cast(ST_Y(location) as numeric), 3), 
       case                   
           when TRUNC(cast(ST_X(location) as numeric), 3) < 0 
           then TRUNC(cast(ST_X(location) as numeric), 3) - 0.001 
           else TRUNC(cast(ST_X(location) as numeric), 3) + 0.001 
       end, 
       case
           when TRUNC(cast(ST_Y(location) as numeric), 3) < 0 
           then TRUNC(cast(ST_Y(location) as numeric), 3) - 0.001 
           else TRUNC(cast(ST_Y(location) as numeric), 3) + 0.001 
       end, 
       4326
   ) as grouped_location
FROM mytable 
WHERE 
location && !bbox!
GROUP BY grouped_location
```

I'm generating a squared global-grid, and AVGing values of points inside it.

Using !bbox! I can get it to use the index :+1:

**Comment by javisantana** [comment]
thanks !
