### ISSUE TITLE
Error when geometry is MultiPoint

### ISSUE THREAD

**Issue by jsanz** [CartoDB/Windshaft#383]
When the query passed to the windshaft on a torque layer contains multipoints the server returns valid layergroup and all but later when asking for a torque json tile it responds with an error like this: 

```
{"errors":["TorqueRenderer: Argument to X() must be a point”]}`
```

Which is actually quite informative but maybe it should complain when calling first to the Maps API.

**Comment by ernesmb** [comment]
There is a customer ticket related to this: SB/6943412
Also Heatmaps are not working, giving the same error.

**Comment by danicarrion** [comment]
Any news about this one?

**Comment by rochoa** [comment]
What would you expect when having a multipoint? To be specific: what would you expect for a query/dataset like: 

```sql
SELECT
ST_Transform(
	ST_Collect(
		ST_GeomFromText('SRID=4326; POINT(0 0)'),
		ST_GeomFromText('SRID=4326; POINT(45 45)')
	),
3857) the_geom_webmercator, 1 cartodb_id
UNION ALL
SELECT ST_Transform(ST_GeomFromText('SRID=4326; POINT(90 45)'), 3857) the_geom_webmercator, 2 cartodb_id
```

Anyway, do you think you can work on a PR for this?
