### ISSUE TITLE
Use the_geom when the_geom_webmercator not present

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/Windshaft#388]
When a user changes the SQL to,

``` sql
SELECT the_geom, number_cats FROM cat_table
```

Windshaft should notice that the_geom_webmercator is not present and make the change to render the_geom instead. We meant to file this ticket 3.5 years ago, but forgot.

cc @javisantana

**Comment by strk** [comment]
There is a `geom_column` element in the layer config: https://github.com/CartoDB/Windshaft/blob/master/doc/MapConfig-1.5.0.md -- introspection could be better done by wrappers, not core.
