### ISSUE TITLE
Support for GeoJSON vector layer

### ISSUE THREAD

**Issue by dgaubert** [CartoDB/Windshaft#397]
We need to add a new type of layer in MapConfig specification. We are going to serve, for example, [GeoJSON](https://en.wikipedia.org/wiki/GeoJSON) tiles. For rendering vector tiles it will be necessary to instantiate the right MapConfig. Vector tiles could be GeoJSON, TopoJSON among other formats that implies rendering in client side.

- [x] Define specification for vector layer. 
- [x] Implement GeoJSON renderer, using vector layer specification.
- [ ] Update documentation with the new specification.

cc @rochoa & @fdansv

**Comment by rochoa** [comment]
@dgaubert can you update this based on current status?
