### ISSUE TITLE
Add some stats info for the agregation endpoint

### ISSUE THREAD

**Issue by xavijam** [CartoDB/Windshaft#398]
- Min value ~~(it could be calculated in frontend)~~.
- Max value ~~(it could be calculated in frontend)~~.
- Number of occurrences.
- Number of categories.
- ~~Avg value (it could be managed with the two previous values)~~.
- Null values.

**Comment by rochoa** [comment]
Done in 8da48c46a0e8242e356b6753a4b86690c331daa3.
