### ISSUE TITLE
Enable empty accept filter for categories

### ISSUE THREAD

**Issue by xavijam** [CartoDB/Windshaft#400]
We would like "reject" all categories without sending all of them through the parameter, it would be great if we add this possibility.

For example:

```
https://:username.cartodb.com/api/v1/map?stat_tag=&filters={%22layers%22:[{%22category_widget_adm0_a3%22:{%22accept%22:[]}}]}
```

It is returning an error:

```
Error creating dashboard instance: Category filter expects to have at least one value in accept or reject arrays
```

**Comment by rochoa** [comment]
Fixed at 450d1493cba7a5fe48a92468b6b8bd6562e06921.
