### ISSUE TITLE
[TILE RENDER ERROR] -- 400: Error: Postgis Plugin: Bad connection

### ISSUE THREAD

**Issue by eltoro** [CartoDB/Windshaft#402]
I'm getting this error intermittently. I have Postgres on another server. It seems to happen when Windshaft has been idle for a while and then starts working. I've tested the database with other clients and JMeter and it never has connection problems. Any Ideas as to what is causing it?

[TILE RENDER ERROR] -- 400: Error: Postgis Plugin: Bad connection

**Comment by rochoa** [comment]
Are you still having this issue?

Can you run with `DEBUG=windshaft*` to see if we can get more details about where the error is coming.

**Comment by strk** [comment]
As I'm also having troubles with debugging `Bad connection`: is `DEBUG=windshaft*` supposed to print more info about the failure ? Is that an env variable ? Which component would be reading it ?

**Comment by Algunenano** [comment]
Stale
