### ISSUE TITLE
[category] When a filter is set with an accept value, that value is not returned when request is done

### ISSUE THREAD

**Issue by xavijam** [CartoDB/Windshaft#403]
So, if we set a filter with:

```
filter: { accept: ["ES"] }
```

When you request data from that widget, that accepted category is not being returned if there are categories with more aggregation value than that.

**Comment by rochoa** [comment]
Are you using `own_filter=1` param when requesting results to the widget?

**Comment by xavijam** [comment]
Wait, this ticket is old, already fixed :)
