### ISSUE TITLE
Add support for date column/type for histogram endpoint

### ISSUE THREAD

**Issue by viddo** [CartoDB/Windshaft#405]
Required for time-series widget, see this example: https://github.com/CartoDB/cartodb.js/blob/877eef878c4e34eabac8a7a516406fc71931d0f8/examples/torque-time-series-widget.html#L215-L269 and in particular the TODO comments that highlight where the current workarounds are used until this is supported.

**Comment by rochoa** [comment]
Datetime columns should be supported already by Windshaft-cartodb's dataviews as per https://github.com/CartoDB/Windshaft-cartodb/blob/27036379dd5acb631f902a247783e70629594696/test/acceptance/widgets/ported/histogram.js#L246.
