### ISSUE TITLE
grid errors Unsupported format json

### ISSUE THREAD

**Issue by danielesevegnani** [CartoDB/Windshaft#408]
I got an error on grid.json request grid({"errors":["Unsupported format json"]});
On a simple MapConfig in examples/viewer/index.html 
```javascript
{
	"version": "1.3.0",
	"layers": [
    {
      "type": "mapnik",
      "options": {
        "sql": "select 1 as id, ST_Buffer(ST_SetSRID(ST_MakePoint(0,0),3857),5e6,4) g",
        "geom_column": "g",
        "cartocss": "#s { polygon-fill: blue; line-color: red; }",
        "cartocss_version": "2.0.1",
        "interactivity": "id"
      }
    }
  ]
}
```
npm test, basic grid json, work correctly.

**Comment by rochoa** [comment]
Hi, I just updated the viewer and readme_server.js. Interactivity should work for your example now :smile: 

Thanks for reporting!!
