### ISSUE TITLE
allow for histograms to be customized in diJSON

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/Windshaft#414]
Right now the `bins` value is ignored when setting up a histogram widget. 

The following would be ideal for creating histograms IMO:

 - [x] No `bins` key means default to Freeman-Diaconis bin calculations
 - [x] `bins: n` gives `n` bins equally spaced over the range of the data (a separate key `scale` could have `equal` or `log` scales for the binning)
 - [ ] `bins: [v1, v2, v3, v4, ..., vn]` gives the `n` bin bounds for `n-1` bins

cc @rochoa

**Comment by rochoa** [comment]
I'm reopening this as `3.` was not implemented yet.

**Comment by rochoa** [comment]
@ohasselblad what would you expect for `3.` if your provided bins cannot carry all data values. I mean: let's say you set `bins: [0, 50, 100]` but then your data has values [-10, 0, 20, 80, 100, 500]. What should happen with -10 and 500? :smiling_imp:

**Comment by ohasselblad** [comment]
:smiling_imp: 
I would say:
1. (preferred) Ignore it and create console warning flag that there are values outside the input bins
2. Automatically add more bins that does this based on `min` -10 and input bins `[0,50,100]`: `[-10,0,50,100,500]`. So adding new bins that do `min` of dataset to min input bin, and max input bin to max value in dataset.

**Comment by ohasselblad** [comment]
btw, the `width_bucket` function returns values outside of range similar to what option 2 above: http://www.postgresql.org/docs/9.3/static/functions-math.html

**Comment by ohasselblad** [comment]
Another option that would be absolutely wonderful, is explained here: https://jakevdp.github.io/blog/2012/09/12/dynamic-programming-in-python/

@stuartlynn discovered this article

**Comment by rochoa** [comment]
Remember that we want to have the whole dataset represented along the current histogram (usually synced with the bounding box) so it's easier to understand what you are looking at compared to the whole dataset. The best way to do that is to have a fixed number of bins and a fixed size for them.

That doesn't mean we could apply that technique to calculate the bins and width for the whole dataset and the reuse those bins/widths for the current view.

**Comment by rochoa** [comment]
This has been superseded by https://github.com/CartoDB/Windshaft-cartodb/issues/495.
