### ISSUE TITLE
[geojson] Investigate empty GeometryCollections

### ISSUE THREAD

**Issue by fdansv** [CartoDB/Windshaft#435]
Sometimes Windshaft includes in tiles GeoJSON elements called `GeometryCollection`, which sometimes table properties, but no geographic data associated to them. I don't know if this is because the_geom is null or something else, but it might be worth looking into it.

See https://github.com/CartoDB/d3.cartodb/issues/102 for reference. Zooming all the way into Madrid (zoom ~18) on the populated places example will return some of these elements.

@dgaubert

**Comment by dgaubert** [comment]
Maybe it's related to [this](http://gis.stackexchange.com/questions/106932/empty-geometries-in-geometrycollection)

BTW I'll take a look.

**Comment by rochoa** [comment]
Feel to reopen if you are still having this issue.
