### ISSUE TITLE
Avoid to calculate columns for every tile in geojson-renderer

### ISSUE THREAD

**Issue by dgaubert** [CartoDB/Windshaft#447]

**Comment by rochoa** [comment]
This was already addressed, right?

**Comment by dgaubert** [comment]
I'm not totally sure, because of [this](https://github.com/CartoDB/Windshaft/blob/master/lib/windshaft/renderers/mapnik/geojson_renderer.js#L81)

**Comment by rochoa** [comment]
Well, I meant doing the `select * from ({sql}) _c limit 0` query that we were doing before, so I'm closing this one.
