### ISSUE TITLE
Don't use underscore object manipulation (e.g: _pluck_) in geojson-renderer

### ISSUE THREAD

**Issue by dgaubert** [CartoDB/Windshaft#448]
In order to avoid **CPU-bound** in Windshaft, we must avoid to use underscore functions like _pluck_ to manipulate query results in _geojson-renderer_. It could be done modifying the _geojson-query_ to return what is expected and it won't needed to manipulate before sending to client.

**Comment by rochoa** [comment]
This no longer applies as GeoJSON tiles support was dropped in https://github.com/CartoDB/Windshaft/pull/563.
