### ISSUE TITLE
Send coordinates relative to tiles. (0..255 or 0..n^2) in geojson-renderer

### ISSUE THREAD

**Issue by dgaubert** [CartoDB/Windshaft#449]
In order to reduce the amount of data sent to client using geojson-renderer, we should implement a way to send geojson coordinates relative to tile instead of web mercator. Also, it reduces client operations with geojson-tiles.

**Comment by rochoa** [comment]
This no longer applies as GeoJSON tiles support was dropped in https://github.com/CartoDB/Windshaft/pull/563.
