### ISSUE TITLE
Add configuration to set base_dir

### ISSUE THREAD

**Issue by strk** [CartoDB/Windshaft#45]
A map's ``base_dir`` is what's used to resolve relative paths used to reference external resources.
When reading the map from standard input the ``base_dir`` is also taken as the map's filename, and as such printed togheter with error messages by Mapnik.

Currently it is set to the dirname of the current working directory at server startup time.

It may have implications for https://github.com/Vizzuality/grainstore/issues/4

**Comment by rochoa** [comment]
I see no need to implement this, closing as has been opened for a while now.
