### ISSUE TITLE
How decoupled is Windshaft from postgis?

### ISSUE THREAD

**Issue by lghamie** [CartoDB/Windshaft#472]
We would probably need to use data from mongo, so I was wondering how possible would it be to make a fork which uses mongo as the data store. 

If possible, could you give any design pointers on how you would implement that?

**Comment by rochoa** [comment]
With some changes you can have a renderer that consumes data from any datasource. I recommend you to check https://github.com/CartoDB/Windshaft/tree/master/lib/windshaft/renderers.

If you still want to keep mapnik as rendering backend you can check: https://github.com/springmeyer/mapnik-mongo

**Comment by lghamie** [comment]
Thanks!
