### ISSUE TITLE
Change query based on zoom level

### ISSUE THREAD

**Issue by lghamie** [CartoDB/Windshaft#476]
I would need to use different queries based on the zoom level.

Should I make three layers that are only shown in the respective zoom level and hide/show them in my web client? Or is there a way to put the three on the same layer and include just one in my client?

Thanks!

**Comment by rochoa** [comment]
Will the different queries produce the same columns + types?

**Comment by lghamie** [comment]
Yes, just different sized features.

**Comment by rochoa** [comment]
Then you can use `!scale_denominator!` token: https://github.com/mapnik/mapnik/wiki/ScaleAndPpi

In combination with https://github.com/CartoDB/cartodb-postgresql/blob/f5f59be5b0f6adb0708b99b1d10032b48a626109/scripts-available/CDB_ZoomFromScale.sql you can know in which zoom level you are:

```
SELECT *, CDB_ZoomFromScale('!scale_denominator!'::numeric) AS zoom FROM your_table
```

HTH.

**Comment by lghamie** [comment]
Thanks!! Really helpful!

**Comment by rochoa** [comment]
yw 😄 .
