### ISSUE TITLE
Layer filtering on 0.40.x

### ISSUE THREAD

**Issue by lghamie** [CartoDB/Windshaft#477]
Hi, I'm using 0.40.x. I created a layergroup with 4 layers.  I'm trying to get each layer rendered separately, but I always get all layers rendered. 

The URLS i'm using are of the form:

`/api/3bfef6bef1c884eb55c1bd35e956fa98/0/14/5534/9871.png`

I can see the "layer" param if I print it in `req2params()` but it doesn't matter if I change it from 0 to any of the other layers, since it always renders all the layers.

Any idea of what I might be doing wrong?

**Comment by rochoa** [comment]
That's a limitation of the current implementation:

> Once a mapnik layer is selected all mapnik layers will get blended. As this may change in the future it is recommended to always select all mapnik layers if you want to select at least one so you will get a consistent behaviour in the future.

https://github.com/CartoDB/Windshaft/blob/e89566452d1a3f22c2ca7384e76de282753fa687/doc/Multilayer-API.md#fetch-tiles-for-a-group-of-blended-layers

**Comment by rochoa** [comment]
There is already support for rendering mapnik layers independently.

**Comment by lghamie** [comment]
Thanks, really helpful!

2016-08-22 10:06 GMT-03:00 Raul Ochoa <notifications@github.com>:
