### ISSUE TITLE
Support for alternative projections in GeoJSON

### ISSUE THREAD

**Issue by fdansv** [CartoDB/Windshaft#490]
At the moment, whenever we're trying to render a map in an alternative projection, like [this examples in Albers](https://mamatablog.carto.com/builder/468a4bc4-7a9a-11e5-b821-0e674067d321/embed?vector=true), each tile request is returning a 400, with an `"Operation on mixed SRID geometries"` error. 

@rochoa

**Comment by rochoa** [comment]
Windshaft already supports different projections, it's a matter of specifying the adequate `"srid"` option.
