### ISSUE TITLE
implications of substitution tokens in `attributes` undefined

### ISSUE THREAD

**Issue by strk** [CartoDB/Windshaft#493]
The documentation for `options.sql` of layer in MapConfig-1.5.0 mentions that implications of tokens substitution in the ``attribtues`` configuration will be documented, but no such referenced documentation exists in the ``attributes`` section.

**Comment by rochoa** [comment]
I forgot to update that references when I added support for substitution tokens: https://github.com/CartoDB/Windshaft/commit/2e1c6cf7edb047f70cf6f5f356956ca550963047.
