### ISSUE TITLE
Adding labels produces a 'this map could not be rendered' warning

### ISSUE THREAD

**Issue by MariaCheca** [CartoDB/Windshaft#497]
@zingbot commented on [Tue Sep 27 2016](https://github.com/CartoDB/cartodb/issues/9910)

Context:
Adding labels to a map in the styling panel

Process: 
> Add points to map
> Click style tab
> Check 'Labels' box
> Add column to derive label
> Select 'Catamaran Regular' Or any newly added font

Expected behavior:
Labels on every dot!

Current result:
'This map is cannot be rendered' warning

![label_issue2](https://cloud.githubusercontent.com/assets/1216307/18886296/4c087bce-84bd-11e6-86a8-8388cc4ae3b7.gif)

**Comment by MariaCheca** [comment]
Moving here because the problem is inside Windshaft, where the [recently added fonts](https://github.com/CartoDB/cartodb/pull/9888) are not supported yet.

When user selects a non supported font, an `api/v1/map?` response like the one below is received:
```
/**/ typeof _cdbc_2113366867_1 === 'function' && _cdbc_2113366867_1({"errors":["style0:12:2 Invalid value for text-face-name, the type font is expected. Catamaran Regular (of type string)  was given."],"errors_with_context":[{"type":"unknown","message":"style0:12:2 Invalid value for text-face-name, the type font is expected. Catamaran Regular (of type string)  was given."}]});
```

For the moment I'll revert the PR with the new fonts until this is fixed :)

**Comment by rochoa** [comment]
Once fonts are installed at system level, they will work.
