### ISSUE TITLE
Does windshaft now depend on cartodb enabled databases ?

### ISSUE THREAD

**Issue by strk** [CartoDB/Windshaft#503]
I get this error upon sending a map config to Windshaft:
```
{"errors":["function cdb_querytablestext(unknown) does not exist"]}
```

Does this mean Windshaft now *requires* a cartodb-enabled database ?
( this wasn't the case until "recently" )

\cc @rochoa @pramsey

**Comment by strk** [comment]
The dep is here:
```
lib/windshaft/utils/query_utils.js:20:        'SELECT * FROM CDB_QueryTablesText($windshaft$',
```

I'm looking at `Windshaft` rather than `Windshaft-CartoDB` to do w/out the whole `CartoDB` infrastructure, is this still a possibility ?

**Comment by javisantana** [comment]
you need to install cartodb-postgres, that's the only dependency

**Comment by strk** [comment]
On Wed, Nov 09, 2016 at 10:31:08AM -0800, javi santana wrote:
> you need to install cartodb-postgres, that's the only dependency

Then it would be worth adding it to the 

# Dependencies

section in the README file

( so far I found out it's just the function in 2 files included
  in the Windshaft testsuite, but I might have missed something )

**Comment by javisantana** [comment]
I think we have those files just to pass tests.

we accept PR's as you probably know

**Comment by rochoa** [comment]
What version are you using?

What do you mean by:
> I get this error upon sending a map config to Windshaft

That function is used optionally based on configuration.

**Comment by strk** [comment]
@rochoa version 2.6.2. By `sending a map config` I mean hitting the `:base_url_mapconfig` endpoint with a `MapConfig` json

**Comment by strk** [comment]
PR ready: #505

**Comment by rochoa** [comment]
Can you be more explicit about:

> hitting the :base_url_mapconfig endpoint with a MapConfig json

BTW, have in mind Windshaft is no longer a service/server, it's just a library as stated in the documentation.

**Comment by strk** [comment]
@rochoa the code using the `cartodb-postgresql` function is in the library:
```
lib/windshaft/utils/query_utils.js:20:        'SELECT * FROM CDB_QueryTablesText($windshaft$',
```

I hadn't researched the exact code path hitting that point, but I'm using the `example/server.js` implementation

**Comment by strk** [comment]
The function in query_utils.js:20 (extractTableNames) is called by MapnikLayerMetadata.prototype.getMetadata in
lib/windshaft/metadata/mapnik-layer-metadata.js:36

I remember that at one point I've added an `affected_tables` key in the `MapConfig` thinking at exactly this issue, basically allowing `MapConfig` editors to figure that information out themselves (it's often already available via other means by editors)

**Comment by strk** [comment]
affected_table is actually still there as of MapConfig 1.5.0: https://github.com/CartoDB/Windshaft/blame/master/doc/MapConfig-1.5.0.md#L121-L124

**Comment by strk** [comment]
I confirm that including `affected_tables` in the `mapnik` layer definition does not prevent the `CDB_QueryTablesText` function from being invoked

**Comment by rochoa** [comment]
a58f7e7 disables the, incorrectly introduced, default behavior of looking for table stats.

Hope that helps, feel free to reopen otherwise.

**Comment by strk** [comment]
I noticed there's no trace of the change in the NEWS file

**Comment by strk** [comment]
So I cannot confirm the fix is effective as I still find this in the logs:
```
ERROR:  function cdb_querytablestext(unknown) does not exist at character 15
```

How can I further debug this ? (and I cannot reopen this myself).
The MapConfig looks like this:
```
{
  "version": "1.5.0",
  "layers": [{"type": "mapnik",
      "options": {
       "cartocss": "#s { marker-width: 10; marker-fill: #a04057; }",
        "sql": "select * from liberia",
        "geom_column": "geom",
        "srid": 4326,
        "cartocss_version": "2.0.0",
        "interactivity": "instance"
      }
    }
  ]
}
```

**Comment by strk** [comment]
Nevermind, I found I had the layerMetadata feature enabled in config. Seems to be fixed now.
