### ISSUE TITLE
[node-v6] [mapnik-v3] Upgrade tilelive-mapnik

### ISSUE THREAD

**Issue by dgaubert** [CartoDB/Windshaft#518]
Use a tilelive-mapnik version that supports Node 6.x and Mapnik 3.x

Is this compatible with Node-v0.10?

Yes.

**Comment by strk** [comment]
Any news on this ? At the time of writing, latest stable Node version is 6.9.5 and latest release is 7.5.0

**Comment by strk** [comment]
I see Windshaft is using custom version of tilelive-mapnik and tilelive-bridge, are they still needed, or could they be swapped back to upstream versions ?

**Comment by dgaubert** [comment]
Done in https://github.com/CartoDB/Windshaft/commit/7086416a60a238aadb1c3fdfd92b26b86e646ab6
