### ISSUE TITLE
google maps torque tiles

### ISSUE THREAD

**Issue by DinakaranS** [CartoDB/Windshaft#523]
Hi,

I am using windshaft for quite a while, its really good. 

Now, i want to add a torque layer to google maps. Is it possible to add a torque layer in google maps using windshaft.

Like 
new google.maps.ImageMapType({

    getTileUrl: function (coord, zoom) {

      return  baseURL + '/' + mapconfig + '/' + token +'/' + zoom + '/' + coord.x + '/' + coord.y + '.png';

    },

    tileSize: new google.maps.Size(256, 256)
  });

**Comment by rochoa** [comment]
Check http://cartodb.github.io/torque/examples/navy_gmaps.html for an example of using Torque tiles with Google Maps.

HTH.
