### ISSUE TITLE
mvt vector tiles for line features

### ISSUE THREAD

**Issue by arethasamuel** [CartoDB/Windshaft#524]
Hello, i'm using the mvt endpoint to serve out vector tiles --> its working great for points and polygons, however with Line Features --> i get this erroneous image (has extra flickering lines)

I am using mapbox-gl.js v0.31.0

Are you familiar with this issue?

![screen shot 2017-01-17 at 5 17 59 pm](https://cloud.githubusercontent.com/assets/12515611/22047044/766fa8f0-dcd9-11e6-9a26-18143dee925a.png)

**Comment by Algunenano** [comment]
This looks like an old issue in mapbox-vector-tile, so I think it has been fixed for a while. It should also works fine using Postgis' ST_AsMVT ([pg-mvt](https://github.com/CartoDB/Windshaft/blob/571528fd5a1e8bcad543f5a0a55b73951c4d1c29/lib/windshaft/renderers/renderer_factory.js#L107)) as backend.
