### ISSUE TITLE
Torque results order is unspecified

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/Windshaft#574]
This test is now broken in some cases (apparently when using PostgreSQL 9.6 instead of 9.5):

```
  1) torque query can hold substitution tokens:
     Uncaught AssertionError: [ anonymous {
    x__uint8: 128,
    y__uint8: 128,
    vals__uint8: [ 3, 2 ],
    dates__uint16: [ 0, 1 ] } ] deepEqual [ { x__uint8: 128,
    y__uint8: 128,
    vals__uint8: [ 2, 3 ],
    dates__uint16: [ 1, 0 ] } ]
      at /home/ubuntu/windshaft/test/acceptance/torque.js:302:20
```

The order of the torque results has changed (but is consistent, note that the date to values correspondence is kept).

This is the query that returns the torque results:

https://github.com/CartoDB/Windshaft/blob/master/lib/windshaft/renderers/torque/renderer.js#L106-L138

The query doesn't specified an order, so PostgreSQL is free to return the results in any order.

We can easily force the results in the order the text expects (by date):

```diff
diff --git a/lib/windshaft/renderers/torque/renderer.js b/lib/windshaft/renderers/torque/renderer.js
index 10b502d..a9b98f6 100644
--- a/lib/windshaft/renderers/torque/renderer.js
+++ b/lib/windshaft/renderers/torque/renderer.js
@@ -133,7 +133,7 @@ Renderer.prototype = {
                 "FROM ({_sql}) i, par p " +
                 "WHERE i.{gcol} && p.b_ext " +
                 stepFilter(attrs) +
-            "GROUP BY xx, yy, d  " +
+            "GROUP BY xx, yy, d ORDER BY d desc" +
             ") cte, par  " +
             "GROUP BY x__uint8, y__uint8; ";
```

But this could affect the performance of the query.

On the other hand we're not relying on the data being ordered by date to render it on the client we could just change the test to not be order dependent and leave the query alone.

So we should check if wherever we use torque tiles we're assuming date order, or if the order doesn't affect our rendering.

**Comment by ramiroaznar** [comment]
This need to be tested before the postgres 10 migration.

**Comment by jgoizueta** [comment]
Hey, I've realised that I was confusing the order of the torque results:

* Our test expects the results in descending date order which seems to be the order we were getting in PostgreSQL 9.5
* With PostgreSQL 9.6 we get the data in ascending date order (which looks nicer to me).

This is a hint that the order is probably irrelevant for the front's usage, but we should check it to be sure. Ideally the front shouldn't depend on the order of the torque data, so we can leave the query as is.

**Comment by jgoizueta** [comment]
For the record, to make the test order-independent:

```diff 
diff --git a/test/acceptance/torque.js b/test/acceptance/torque.js
index 7e35a17..6033986 100644
--- a/test/acceptance/torque.js
+++ b/test/acceptance/torque.js
@@ -295,7 +295,14 @@ describe('torque', function() {
             SubstitutionTokens.replace = replaceFn;

             assert.ok(!err, err);
-            assert.deepEqual(torqueTile, [{ x__uint8: 128, y__uint8: 128, vals__uint8: [2,3], dates__uint16: [1,0] }]);
+            assert.equal(torqueTile.length, 1);
+            assert.equal(torqueTile[0].x__uint8, 128);
+            assert.equal(torqueTile[0].y__uint8, 128);
+            let ordered_dates = torqueTile[0].dates__uint16.sort();
+            let indices = Array(torqueTile[0].dates__uint16.length).fill().map((i,j)=>j);
+            let values_order_by_date = indices.map(i=>[torqueTile[0].dates__uint16[i], torqueTile[0].vals__uint8[i]]).sort().map(([d,v])=>v);
+            assert.deepEqual(ordered_dates, [0,1]);
+            assert.deepEqual(values_order_by_date, [3,2]);

             assert.equal(expectedSubstitutionTokens.length, 0);
```

**Comment by Algunenano** [comment]
Working on this now as I have a dependent ticket I'd like to test locally and several tests fail due to this (ok in travis).

**Comment by Algunenano** [comment]
Affects both windshaft and windshaft-cartodb

**Comment by Algunenano** [comment]
Windshaft PR: https://github.com/CartoDB/Windshaft/pull/581
Windshaft-Cartodb: https://github.com/CartoDB/Windshaft-cartodb/pull/815

**Comment by Algunenano** [comment]
Update: @rochoa is preparing some tests in Windshaft to generate some images from torque tiles and be able to compare if there are differences because of the order, that is PG9.5 and PG10

**Comment by Algunenano** [comment]
Updated both PRs

**Comment by ramiroaznar** [comment]
Hey @Algunenano what is the status of this? Should @enekid continue working on this?

**Comment by Algunenano** [comment]
Hi @ramiroaznar, it's pending review. If @enekid can have a look it'd great, if not I think we would have to wait for @dgaubert or @jgoizueta

**Comment by ramiroaznar** [comment]
Thanks! We wait for them then. :-)

**Comment by ramiroaznar** [comment]
:boom:
