### ISSUE TITLE
Map label gets cut in Voyager basemap in a certain level of zoom

### ISSUE THREAD

**Issue by jesusbotella** [CartoDB/Windshaft#591]
I have found that there is a label that is cut at zoom level 13 in Voyager basemap. It is located in the south of Madrid, I attach a screenshot to show the case where it fails.

![screen shot 2018-01-30 at 12 06 19](https://user-images.githubusercontent.com/4319728/35563221-55077aec-05b6-11e8-87da-63ac4132df09.png)

**Comment by Algunenano** [comment]
Not a Windshaft issue

**Comment by dgaubert** [comment]
Please @jesusbotella, could you open a new issue in https://github.com/CartoDB/basemap-styles/issues??

Thanks in advance!
