### ISSUE TITLE
Building Errors

### ISSUE THREAD

**Issue by nicoali** [CartoDB/Windshaft#598]
I've this error:

npm ERR! Linux 4.1.19-v7+
npm ERR! argv "/home/testflusso/.nvm/versions/node/v6.9.2/bin/node" "/home/testflusso/.nvm/versions/node/v6.9.2/bin/npm" "install"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! path /home/testflusso/Windshaft-cartodb/Windshaft/node_modules/.staging/abbrev-ea4d9d56
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/home/testflusso/Windshaft-cartodb/Windshaft/node_modules/.staging/abbrev-ea4d9d56' -> '/home/testflusso/Windshaft-cartodb/Windshaft/node_modules/@carto/mapnik/node_modules/abbrev'
npm ERR! enoent ENOENT: no such file or directory, rename '/home/testflusso/Windshaft-cartodb/Windshaft/node_modules/.staging/abbrev-ea4d9d56' -> '/home/testflusso/Windshaft-cartodb/Windshaft/node_modules/@carto/mapnik/node_modules/abbrev'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /home/testflusso/Windshaft-cartodb/Windshaft/npm-debug.log

This is the log: 
[npm-debug.log](https://github.com/CartoDB/Windshaft/files/1738136/npm-debug.log)

**Comment by rlxmp** [comment]
Same here.

**Comment by nicoali** [comment]
i did 
sudo visudo and edited :
#Defaults       env_reset
#Defaults       secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:$
Defaults        env_keep += "PATH CPLUS_INCLUDE_PATH C_INCLUDE_PATH"

error disappeared

**Comment by Algunenano** [comment]
Stale
