### ISSUE TITLE
buffersize is parsed as integer without checking

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/Windshaft#631]
When [validating a bufersize](https://github.com/CartoDB/Windshaft/blob/master/lib/windshaft/models/mapconfig.js#L122-L124) we should check it is actually a valid integer. 

Now something like `1E300` will be admitted as valid with the value `1` (as given by `parseInt`) which users might find surprising (well, it did surprise me!)

**Comment by dgaubert** [comment]
Hey @jgoizueta!

taking a look into this, I agree that you find it surprising. But I can't see any issue:

https://github.com/CartoDB/Windshaft/blob/master/lib/windshaft/models/mapconfig.js#L114-L120

which it returns:

```
$ node
> parseInt(1e10, 10)
10000000000
```

Apart from being a number with no sense. I don't see any problem.

**Comment by jgoizueta** [comment]
🤔 Maybe I checked it in an older node version and ti worked differently? (i swear it returned 1, not 10000000000)

**Comment by jgoizueta** [comment]
Can `buffersize` arrive as a String? I see the problem occurs with strings: 
```
> parseInt('1e10', 10)
1
```

**Comment by dgaubert** [comment]
From documentation, buffer-size should be a number:
https://github.com/CartoDB/Windshaft/blob/master/doc/MapConfig-1.7.0.md

So, I'd respond with an error if buffer-size comes as `string`. Do you agree??

**Comment by jgoizueta** [comment]
Yes! 👍

**Comment by dgaubert** [comment]
Fix deployed in production
