### ISSUE TITLE
Test socket hangups

### ISSUE THREAD

**Issue by strk** [CartoDB/Windshaft#76]
I don't know what happens when requests get aborted on the client side.
Supposedly the server should be notified about that (with a socket hangup?) but I don't think we're handling that in any way. Ideally we should avoid doing useless work. What's useful and what not may not be straightforward in that we queue some request responses while waiting for the renderer cache to render a whole metatile, but this is definitely something we should look into.

**Comment by rochoa** [comment]
This should be addressed in https://github.com/CartoDB/Windshaft/issues/176
